export default [
  ["aspect-[value]", ["aspect-ratio: value"]],
  ["columns-[value]", ["columns: value"]],
  ["object-[value]", ["object-position: value"]],
  ["object-left-[value]", ["object-position: value"]],
  ["object-right-[value]", ["object-position: value"]],
  ["inset-[value]", ["inset: value"]],
  ["inset-x-[value]", ["left: value", "right: value"]],
  ["inset-y-[value]", ["top: value", "bottom: value"]],
  ["start-[value]", ["inset-inline-start: value"]],
  ["end-[value]", ["inset-inline-end: value"]],
  ["top-[value]", ["top: value"]],
  ["right-[value]", ["right: value"]],
  ["bottom-[value]", ["bottom: value"]],
  ["left-[value]", ["left: value"]],
  ["z-[value]", ["z-index: value"]],
  ["basis-[value]", ["flex-basis: value"]],
  ["flex-[value]", ["flex: value"]],
  ["grow-[value]", ["flex-grow: value"]],
  ["shrink-[value]", ["flex-shrink: value"]],
  ["order-[value]", ["order: value"]],
  ["grid-cols-[value]", ["grid-template-columns: value"]],
  ["col-[value]", ["grid-column: value"]],
  ["col-span-[value]", ["grid-column: value"]],
  ["col-start-[value]", ["grid-column-start: value"]],
  ["col-end-[value]", ["grid-column-end: value"]],
  ["grid-rows-[value]", ["grid-template-rows: value"]],
  ["row-[value]", ["grid-row: value"]],
  ["row-span-[value]", ["grid-row: value"]],
  ["row-start-[value]", ["grid-row-start: value"]],
  ["row-end-[value]", ["grid-row-end: value"]],
  ["auto-cols-[value]", ["grid-auto-columns: value"]],
  ["auto-rows-[value]", ["grid-auto-rows: value"]],
  ["gap-[value]", ["gap: value"]],
  ["gap-x-[value]", ["column-gap: value"]],
  ["gap-y-[value]", ["row-gap: value"]],
  ["p-[value]", ["padding: value"]],
  ["px-[value]", ["padding-left: value", "padding-right: value"]],
  ["py-[value]", ["padding-top: value", "padding-bottom: value"]],
  ["ps-[value]", ["padding-inline-start: value"]],
  ["pe-[value]", ["padding-inline-end: value"]],
  ["pt-[value]", ["padding-top: value"]],
  ["pr-[value]", ["padding-right: value"]],
  ["pb-[value]", ["padding-bottom: value"]],
  ["pl-[value]", ["padding-left: value"]],
  ["m-[value]", ["margin: value"]],
  ["mx-[value]", ["margin-left: value", "margin-right: value"]],
  ["my-[value]", ["margin-top: value", "margin-bottom: value"]],
  ["ms-[value]", ["margin-inline-start: value"]],
  ["me-[value]", ["margin-inline-end: value"]],
  ["mt-[value]", ["margin-top: value"]],
  ["mr-[value]", ["margin-right: value"]],
  ["mb-[value]", ["margin-bottom: value"]],
  ["ml-[value]", ["margin-left: value"]],
  ["w-[value]", ["width: value"]],
  ["min-w-[value]", ["min-width: value"]],
  ["max-w-[value]", ["max-width: value"]],
  ["max-w-screen-[value]", ["max-width: value"]],
  ["h-[value]", ["height: value"]],
  ["min-h-[value]", ["min-height: value"]],
  ["max-h-[value]", ["max-height: value"]],
  ["font-[value]", ["font-family: value"]],
  ["text-[value]", ["font-size: value"]],
  ["font-[value]", ["font-weight: value"]],
  ["tracking-[value]", ["letter-spacing: value"]],
  [
    "line-clamp-[value]",
    [
      "overflow: value",
      "display: value",
      "-webkit-box-orient: value",
      "-webkit-line-clamp: value",
    ],
  ],
  ["leading-[value]", ["line-height: value"]],
  ["list-image-[value]", ["list-style-image: value"]],
  ["list-[value]", ["list-style-type: value"]],
  ["text-[value]", ["color: value"]],
  ["decoration-[value]", ["text-decoration-color: value"]],
  ["decoration-[value]", ["text-decoration-thickness: value"]],
  ["decoration-from-[value]", ["text-decoration-thickness: value"]],
  ["underline-offset-[value]", ["text-underline-offset: value"]],
  ["indent-[value]", ["text-indent: value"]],
  ["align-[value]", ["vertical-align: value"]],
  ["align-text-[value]", ["vertical-align: value"]],
  ["content-[value]", ["content: value"]],
  ["bg-[value]", ["background-color: value"]],
  ["bg-[value]", ["background-position: value"]],
  ["bg-left-[value]", ["background-position: value"]],
  ["bg-right-[value]", ["background-position: value"]],
  ["bg-[value]", ["background-size: value"]],
  ["bg-[value]", ["background-image: value"]],
  ["rounded-[value]", ["border-radius: value"]],
  ["", []],
  [
    "rounded-s-[value]",
    ["border-start-start-radius: value", "border-end-start-radius: value"],
  ],
  [
    "rounded-e-[value]",
    ["border-start-end-radius: value", "border-end-end-radius: value"],
  ],
  [
    "rounded-t-[value]",
    ["border-top-left-radius: value", "border-top-right-radius: value"],
  ],
  [
    "rounded-r-[value]",
    ["border-top-right-radius: value", "border-bottom-right-radius: value"],
  ],
  [
    "rounded-b-[value]",
    ["border-bottom-right-radius: value", "border-bottom-left-radius: value"],
  ],
  [
    "rounded-l-[value]",
    ["border-top-left-radius: value", "border-bottom-left-radius: value"],
  ],
  ["rounded-ss-[value]", ["border-start-start-radius: value"]],
  ["rounded-se-[value]", ["border-start-end-radius: value"]],
  ["rounded-ee-[value]", ["border-end-end-radius: value"]],
  ["rounded-es-[value]", ["border-end-start-radius: value"]],
  ["rounded-tl-[value]", ["border-top-left-radius: value"]],
  ["rounded-tr-[value]", ["border-top-right-radius: value"]],
  ["rounded-br-[value]", ["border-bottom-right-radius: value"]],
  ["rounded-bl-[value]", ["border-bottom-left-radius: value"]],
  ["border-[value]", ["border-width: value"]],
  [
    "border-x-[value]",
    ["border-left-width: value", "border-right-width: value"],
  ],
  ["border-[value]", ["border-left-width: value", "border-right-width: value"]],
  [
    "border-y-[value]",
    ["border-top-width: value", "border-bottom-width: value"],
  ],
  ["border-[value]", ["border-top-width: value", "border-bottom-width: value"]],
  ["border-s-[value]", ["border-inline-start-width: value"]],
  ["border-[value]", ["border-inline-start-width: value"]],
  ["border-e-[value]", ["border-inline-end-width: value"]],
  ["border-[value]", ["border-inline-end-width: value"]],
  ["border-t-[value]", ["border-top-width: value"]],
  ["border-[value]", ["border-top-width: value"]],
  ["border-r-[value]", ["border-right-width: value"]],
  ["border-[value]", ["border-right-width: value"]],
  ["border-b-[value]", ["border-bottom-width: value"]],
  ["border-[value]", ["border-bottom-width: value"]],
  ["border-l-[value]", ["border-left-width: value"]],
  ["border-[value]", ["border-left-width: value"]],
  ["border-[value]", ["border-color: value"]],
  [
    "border-x-[value]",
    ["border-left-color: value", "border-right-color: value"],
  ],
  [
    "border-y-[value]",
    ["border-top-color: value", "border-bottom-color: value"],
  ],
  ["border-s-[value]", ["border-inline-start-color: value"]],
  ["border-e-[value]", ["border-inline-end-color: value"]],
  ["border-t-[value]", ["border-top-color: value"]],
  ["border-r-[value]", ["border-right-color: value"]],
  ["border-b-[value]", ["border-bottom-color: value"]],
  ["border-l-[value]", ["border-left-color: value"]],
  ["outline-[value]", ["outline-width: value"]],
  ["outline-[value]", ["outline-color: value"]],
  ["outline-offset-[value]", ["outline-offset: value"]],
  ["shadow-[value]", ["box-shadow: value"]],
  ["opacity-[value]", ["opacity: value"]],
  ["blur-[value]", ["filter: value"]],
  ["brightness-[value]", ["filter: value"]],
  ["contrast-[value]", ["filter: value"]],
  ["drop-shadow-[value]", ["filter: value"]],
  ["drop-[value]", ["filter: value"]],
  ["grayscale-[value]", ["filter: grayscale(value)"]],
  ["-[value]", ["filter: grayscale(value)"]],
  ["hue-rotate-[value]", ["filter: hue-rotate(0deg)"]],
  ["hue-rotate-[value]", ["filter: hue-rotate(15deg)"]],
  ["hue-rotate-[value]", ["filter: hue-rotate(30deg)"]],
  ["hue-rotate-[value]", ["filter: hue-rotate(60deg)"]],
  ["hue-rotate-[value]", ["filter: hue-rotate(90deg)"]],
  ["hue-rotate-[value]", ["filter: hue-rotate(180deg)"]],
  ["invert-[value]", ["filter: value"]],
  ["saturate-[value]", ["filter: value"]],
  ["sepia-[value]", ["filter: value"]],
  ["backdrop-blur-[value]", ["backdrop-filter: value"]],
  ["backdrop-[value]", ["backdrop-filter: value"]],
  ["backdrop-brightness-[value]", ["backdrop-filter: value"]],
  ["backdrop-contrast-[value]", ["backdrop-filter: value"]],
  ["backdrop-grayscale-[value]", ["backdrop-filter: grayscale(value)"]],
  ["backdrop-[value]", ["backdrop-filter: grayscale(value)"]],
  ["backdrop-hue-rotate-[value]", ["backdrop-filter: hue-rotate(0deg)"]],
  ["backdrop-hue-rotate-[value]", ["backdrop-filter: hue-rotate(15deg)"]],
  ["backdrop-hue-rotate-[value]", ["backdrop-filter: hue-rotate(30deg)"]],
  ["backdrop-hue-rotate-[value]", ["backdrop-filter: hue-rotate(60deg)"]],
  ["backdrop-hue-rotate-[value]", ["backdrop-filter: hue-rotate(90deg)"]],
  ["backdrop-hue-rotate-[value]", ["backdrop-filter: hue-rotate(180deg)"]],
  ["backdrop-invert-[value]", ["backdrop-filter: value"]],
  ["backdrop-opacity-[value]", ["backdrop-filter: value"]],
  ["backdrop-saturate-[value]", ["backdrop-filter: value"]],
  ["backdrop-sepia-[value]", ["backdrop-filter: value"]],
  ["border-spacing-[value]", ["border-spacing: value"]],
  ["border-spacing-x-[value]", ["border-spacing: value"]],
  ["border-spacing-y-[value]", ["border-spacing: value"]],
  ["transition-[value]", ["transition-property: value"]],
  [
    "transition-[value]",
    [
      "transition-property: value",
      "transition-timing-function: value",
      "transition-duration: value",
    ],
  ],
  ["duration-[value]", ["transition-duration: value"]],
  ["ease-[value]", ["transition-timing-function: value"]],
  ["delay-[value]", ["transition-delay: value"]],
  ["scale-[value]", ["transform: scale(value)"]],
  ["scale-x-[value]", ["transform: scaleX(value)"]],
  ["scale-y-[value]", ["transform: scaleY(value)"]],
  ["rotate-[value]", ["transform: rotate(value)"]],
  ["translate-x-[value]", ["transform: translateX(value)"]],
  ["translate-y-[value]", ["transform: translateY(value)"]],
  ["skew-x-[value]", ["transform: skewX(value)"]],
  ["skew-y-[value]", ["transform: skewY(value)"]],
  ["origin-[value]", ["transform-origin: value"]],
  ["origin-top-[value]", ["transform-origin: value"]],
  ["origin-bottom-[value]", ["transform-origin: value"]],
  ["accent-[value]", ["accent-color: value"]],
  ["cursor-[value]", ["cursor: value"]],
  ["caret-[value]", ["caret-color: value"]],
  ["scroll-m-[value]", ["scroll-margin: value"]],
  [
    "scroll-mx-[value]",
    ["scroll-margin-left: value", "scroll-margin-right: value"],
  ],
  [
    "scroll-my-[value]",
    ["scroll-margin-top: value", "scroll-margin-bottom: value"],
  ],
  ["scroll-ms-[value]", ["scroll-margin-inline-start: value"]],
  ["scroll-me-[value]", ["scroll-margin-inline-end: value"]],
  ["scroll-mt-[value]", ["scroll-margin-top: value"]],
  ["scroll-mr-[value]", ["scroll-margin-right: value"]],
  ["scroll-mb-[value]", ["scroll-margin-bottom: value"]],
  ["scroll-ml-[value]", ["scroll-margin-left: value"]],
  ["scroll-p-[value]", ["scroll-padding: value"]],
  [
    "scroll-px-[value]",
    ["scroll-padding-left: value", "scroll-padding-right: value"],
  ],
  [
    "scroll-py-[value]",
    ["scroll-padding-top: value", "scroll-padding-bottom: value"],
  ],
  ["scroll-ps-[value]", ["scroll-padding-inline-start: value"]],
  ["scroll-pe-[value]", ["scroll-padding-inline-end: value"]],
  ["scroll-pt-[value]", ["scroll-padding-top: value"]],
  ["scroll-pr-[value]", ["scroll-padding-right: value"]],
  ["scroll-pb-[value]", ["scroll-padding-bottom: value"]],
  ["scroll-pl-[value]", ["scroll-padding-left: value"]],
  ["will-change-[value]", ["will-change: value"]],
  ["fill-[value]", ["fill: value"]],
  ["stroke-[value]", ["stroke: value"]],
  ["stroke-[value]", ["stroke-width: value"]],
];
