export default {
  ":hover": "hover",
  ":focus": "focus",
  ":focus-within": "focus-within",
  ":focus-visible": "focus-visible",
  ":active": "active",
  ":visited": "visited",
  ":target": "target",
  ":first-child": "first",
  ":last-child": "last",
  ":only-child": "only",
  ":nth-child(odd)": "odd",
  ":nth-child(even)": "even",
  ":first-of-type": "first-of-type",
  ":last-of-type": "last-of-type",
  ":only-of-type": "only-of-type",
  ":empty": "empty",
  ":disabled": "disabled",
  ":enabled": "enabled",
  ":checked": "checked",
  ":indeterminate": "indeterminate",
  ":default": "default",
  ":required": "required",
  ":valid": "valid",
  ":invalid": "invalid",
  ":in-range": "in-range",
  ":out-of-range": "out-of-range",
  ":placeholder-shown": "placeholder-shown",
  ":autofill": "autofill",
  ":read-only": "read-only",
  "::before": "before",
  "::after": "after",
  "::first-letter": "first-letter",
  "::first-line": "first-line",
  "::marker": "marker",
  "::selection": "selection",
  "::file-selector-button": "file",
  "::backdrop": "backdrop",
  "::placeholder": "placeholder",
  "@media (min-width: 640px)": "sm",
  "@media (min-width: 768px)": "md",
  "@media (min-width: 1024px)": "lg",
  "@media (min-width: 1280px)": "xl",
  "@media (min-width: 1536px)": "2xl",
  "@media (min-width: \u2026)": "min-[\u2026]",
  "@media not all and (min-width: 640px)": "max-sm",
  "@media not all and (min-width: 768px)": "max-md",
  "@media not all and (min-width: 1024px)": "max-lg",
  "@media not all and (min-width: 1280px)": "max-xl",
  "@media not all and (min-width: 1536px)": "max-2xl",
  "@media (max-width: \u2026)": "max-[\u2026]",
  "@media (prefers-color-scheme: dark)": "dark",
  "@media (orientation: portrait)": "portrait",
  "@media (orientation: landscape)": "landscape",
  "@media (prefers-reduced-motion: no-preference)": "motion-safe",
  "@media (prefers-reduced-motion: reduce)": "motion-reduce",
  "@media (prefers-contrast: more)": "contrast-more",
  "@media (prefers-contrast: less)": "contrast-less",
  "@media print": "print",
  "@supports (value)": "supports-[value]",
  '[aria-checked="true"]': "aria-checked",
  '[aria-disabled="true"]': "aria-disabled",
  '[aria-expanded="true"]': "aria-expanded",
  '[aria-hidden="true"]': "aria-hidden",
  '[aria-pressed="true"]': "aria-pressed",
  '[aria-readonly="true"]': "aria-readonly",
  '[aria-required="true"]': "aria-required",
  '[aria-selected="true"]': "aria-selected",
  "[aria-value]": "aria-[value]",
  "[data-value]": "data-[value]",
  '[dir="rtl"] ': "rtl",
  '[dir="ltr"] ': "ltr",
  "[open]": "open",
};
