export default {
  "Acc(<custom-param>)": ["accent-color: value"],
  "Ai(<custom-param>)": ["align-items: value"],
  "Ac(<custom-param>)": ["align-content: value"],
  "As(<custom-param>)": ["align-self: value"],
  "Anim(<value> or <custom-param>)": ["animation: value"],
  "Animdel(<value> or <custom-param>)": ["animation-delay: value"],
  "Animdir(<custom-param>)": ["animation-direction: value"],
  "Animdur(<value> or <custom-param>)": ["animation-duration: value"],
  "Animfm(<custom-param>)": ["animation-fill-mode: value"],
  "Animic(<value> or <custom-param>)": ["animation-iteration-count: value"],
  "Animn(<value> or <custom-param>)": ["animation-name: value"],
  "Animps(<custom-param>)": ["animation-play-state: value"],
  "Animtf(<custom-param>)": ["animation-timing-function: value"],
  "Ap(<custom-param>)": ["appearance: value"],
  "Ar(<custom-param>)": ["aspect-ratio: value"],
  "Bd(<custom-param>)": ["border: value"],
  "Bdx(<custom-param>)": ["border-left: value", "border-right: value"],
  "Bdy(<custom-param>)": ["border-top: value", "border-bottom: value"],
  "Bdt(<custom-param>)": ["border-top: value"],
  "Bdend(<custom-param>)": ["border-right: value"],
  "Bdb(<custom-param>)": ["border-bottom: value"],
  "Bdstart(<custom-param>)": ["border-left: value"],
  "Bdc(<value> or <custom-param>)": ["border-color: value"],
  "Bdtc(<value> or <custom-param>)": ["border-top-color: value"],
  "Bdendc(<value> or <custom-param>)": ["border-right-color: value"],
  "Bdbc(<value> or <custom-param>)": ["border-bottom-color: value"],
  "Bdstartc(<value> or <custom-param>)": ["border-left-color: value"],
  "Bdsp(<value>+ or <custom-param>)": ["border-spacing: value1 value2"],
  "Bds(<custom-param>)": ["border-style: value"],
  "Bdts(<custom-param>)": ["border-top-style: value"],
  "Bdends(<custom-param>)": ["border-right-style: value"],
  "Bdbs(<custom-param>)": ["border-bottom-style: value"],
  "Bdstarts(<custom-param>)": ["border-left-style: value"],
  "Bdw(<value> or <custom-param>)": ["border-width: value"],
  "Bdtw(<value> or <custom-param>)": ["border-top-width: value"],
  "Bdendw(<value> or <custom-param>)": ["border-right-width: value"],
  "Bdbw(<value> or <custom-param>)": ["border-bottom-width: value"],
  "Bdstartw(<value> or <custom-param>)": ["border-left-width: value"],
  "Bdrs(<value> or <custom-param>)": ["border-radius: value"],
  "Bdrstend(<value> or <custom-param>)": ["border-top-right-radius: value"],
  "Bdrsbend(<value> or <custom-param>)": ["border-bottom-right-radius: value"],
  "Bdrsbstart(<value> or <custom-param>)": ["border-bottom-left-radius: value"],
  "Bdrststart(<value> or <custom-param>)": ["border-top-left-radius: value"],
  "Bkdp(<custom-param>)": ["backdrop-filter: value"],
  "BkdpBlur(<value> or <custom-param>)": ["backdrop-filter: blur(value)"],
  "BkdpBrightness(<value> or <custom-param>)": [
    "backdrop-filter: brightness(value)",
  ],
  "BkdpContrast(<value> or <custom-param>)": [
    "backdrop-filter: contrast(value)",
  ],
  "BkdpDropshadow(<custom-param>)": ["backdrop-filter: drop-shadow(value)"],
  "BkdpGrayscale(<value> or <custom-param>)": [
    "backdrop-filter: grayscale(value)",
  ],
  "BkdpHueRotate(<value> or <custom-param>)": [
    "backdrop-filter: hue-rotate(value)",
  ],
  "BkdpInvert(<value> or <custom-param>)": ["backdrop-filter: invert(value)"],
  "BkdpOpacity(<value> or <custom-param>)": ["backdrop-filter: opacity(value)"],
  "BkdpSaturate(<value> or <custom-param>)": [
    "backdrop-filter: saturate(value)",
  ],
  "BkdpSepia(<value> or <custom-param>)": ["backdrop-filter: sepia(value)"],
  "Bg(<custom-param>)": ["background: value"],
  "Bgbm(<custom-param>)": ["background-blend-mode: value"],
  "Bgi(<custom-param>)": ["background-image: value"],
  "Bgc(<value> or <custom-param>)": ["background-color: value"],
  "Bgcp(<custom-param>)": ["background-clip: value"],
  "Bgo(<custom-param>)": ["background-origin: value"],
  "Bgz(<value> or <custom-param>)": ["background-size: value"],
  "Bga(<custom-param>)": ["background-attachment: value"],
  "Bgp(<value>+ or <custom-param>)": ["background-position: value1 value2"],
  "Bgpx(<value> or <custom-param>)": ["background-position-x: value"],
  "Bgpy(<value> or <custom-param>)": ["background-position-y: value"],
  "Bgr(<custom-param>)": ["background-repeat: value"],
  "Bdcl(<custom-param>)": ["border-collapse: value"],
  "Bxdb(<custom-param>)": ["box-decoration-break: value"],
  "Bxz(<custom-param>)": ["box-sizing: value"],
  "Bxsh(<custom-param>)": ["box-shadow: value"],
  "Ba(<custom-param>)": ["break-after: value"],
  "Bb(<custom-param>)": ["break-before: value"],
  "Bi(<custom-param>)": ["break-inside: value"],
  "Cac(<custom-param>)": ["caret-color: value"],
  "Cl(<custom-param>)": ["clear: value"],
  "Cp(<custom-param>)": ["clip-path: value"],
  "C(<value> or <custom-param>)": ["color: value"],
  "Colm(<value> or <custom-param>)": ["columns: value"],
  "Colmc(<value> or <custom-param>)": ["column-count: value"],
  "Colmf(<custom-param>)": ["column-fill: value"],
  "Colmg(<value> or <custom-param>)": ["column-gap: value"],
  "Colmr(<value> or <custom-param>)": ["column-rule: value"],
  "Colmrc(<custom-param>)": ["column-rule-color: value"],
  "Colmrs(<custom-param>)": ["column-rule-style: value"],
  "Colmrw(<custom-param>)": ["column-rule-width: value"],
  "Colms(<custom-param>)": ["column-span: value"],
  "Colmw(<value> or <custom-param>)": ["column-width: value"],
  "Ctn(<custom-param>)": ["contain: value"],
  "ContName(<value> or <custom-param>)": ["container-name: value"],
  "ContType(<custom-param>)": ["container-type: value"],
  "Cnt(<value> or <custom-param>)": ["content: value"],
  "Cur(<custom-param>)": ["cursor: value"],
  "D(<custom-param>)": ["display: value"],
  "Fil(<custom-param>)": ["filter: value"],
  "Blur(<value> or <custom-param>)": ["filter: blur(value)"],
  "Brightness(<value> or <custom-param>)": ["filter: brightness(value)"],
  "Contrast(<value> or <custom-param>)": ["filter: contrast(value)"],
  "Dropshadow(<custom-param>)": ["filter: drop-shadow(value)"],
  "Grayscale(<value> or <custom-param>)": ["filter: grayscale(value)"],
  "HueRotate(<value> or <custom-param>)": ["filter: hue-rotate(value)"],
  "Invert(<value> or <custom-param>)": ["filter: invert(value)"],
  "Opacity(<value> or <custom-param>)": ["filter: opacity(value)"],
  "Saturate(<value> or <custom-param>)": ["filter: saturate(value)"],
  "Sepia(<value> or <custom-param>)": ["filter: sepia(value)"],
  "Flx(<custom-param>)": ["flex: value"],
  "Fx(<custom-param>)": ["flex: value"],
  "Flxg(<value> or <custom-param>)": ["flex-grow: value"],
  "Fxg(<value> or <custom-param>)": ["flex-grow: value"],
  "Flxs(<value> or <custom-param>)": ["flex-shrink: value"],
  "Fxs(<value> or <custom-param>)": ["flex-shrink: value"],
  "Flxb(<value> or <custom-param>)": ["flex-basis: value"],
  "Fxb(<value> or <custom-param>)": ["flex-basis: value"],
  "Fld(<custom-param>)": ["flex-direction: value"],
  "Fxd(<custom-param>)": ["flex-direction: value"],
  "Flf(<custom-param>)": ["flex-flow: value"],
  "Fxf(<custom-param>)": ["flex-flow: value"],
  "Ga(<custom-param>)": ["grid-area: value"],
  "Gac(<value> or <custom-param>)": ["grid-auto-columns: value"],
  "Gaf(<custom-param>)": ["grid-auto-flow: value"],
  "Gar(<value> or <custom-param>)": ["grid-auto-rows: value"],
  "Gc(<value> or <custom-param>)": ["grid-column: value"],
  "Gce(<value> or <custom-param>)": ["grid-column-end: value"],
  "Gcs(<value> or <custom-param>)": ["grid-column-start: value"],
  "Gr(<value> or <custom-param>)": ["grid-row: value"],
  "Gre(<value> or <custom-param>)": ["grid-row-end: value"],
  "Grs(<value> or <custom-param>)": ["grid-row-start: value"],
  "Gt(<custom-param>)": ["grid-template: value"],
  "Gta(<custom-param>)": ["grid-template-areas: value"],
  "Gtc(<custom-param>)": ["grid-template-columns: value"],
  "Gtr(<custom-param>)": ["grid-template-rows: value"],
  "Or(<value> or <custom-param>)": ["order: value"],
  "Jc(<custom-param>)": ["justify-content: value"],
  "Ji(<custom-param>)": ["justify-items: value"],
  "Js(<custom-param>)": ["justify-self: value"],
  "Flw(<custom-param>)": ["flex-wrap: value"],
  "Fxw(<custom-param>)": ["flex-wrap: value"],
  "Fl(<custom-param>)": ["float: value"],
  "Ff(<custom-param>)": ["font-family: value"],
  "Fw(<custom-param>)": ["font-weight: value"],
  "Fk(<custom-param>)": ["font-kerning: value"],
  "Fz(<value> or <custom-param>)": ["font-size: value"],
  "Fst(<value> or <custom-param>)": ["font-stretch: value"],
  "Fs(<custom-param>)": ["font-style: value"],
  "Fv(<custom-param>)": ["font-variant: value"],
  "Gp(<value> or <custom-param>)": ["gap: value"],
  "Rowg(<value> or <custom-param>)": ["row-gap: value"],
  "H(<value> or <custom-param>)": ["height: value"],
  "Hy(<custom-param>)": ["hyphens: value"],
  "Ior(<custom-param>)": ["image-orientation: value"],
  "Iren(<custom-param>)": ["image-rendering: value"],
  "In(<value> or <custom-param>)": ["inset: value"],
  "Iso(<custom-param>)": ["isolation: value"],
  "Lts(<value> or <custom-param>)": ["letter-spacing: value"],
  "List(<custom-param>)": ["list-style-type: value"],
  "Lisp(<custom-param>)": ["list-style-position: value"],
  "Lisi(<custom-param>)": ["list-style-image: value"],
  "Lh(<value> or <custom-param>)": ["line-height: value"],
  "M(<value> or <custom-param>)": ["margin: value"],
  "Mx(<value> or <custom-param>)": [
    "margin-left: value",
    "margin-right: value",
  ],
  "My(<value> or <custom-param>)": [
    "margin-top: value",
    "margin-bottom: value",
  ],
  "Mt(<value> or <custom-param>)": ["margin-top: value"],
  "Mend(<value> or <custom-param>)": ["margin-right: value"],
  "Mb(<value> or <custom-param>)": ["margin-bottom: value"],
  "Mstart(<value> or <custom-param>)": ["margin-left: value"],
  "Mah(<value> or <custom-param>)": ["max-height: value"],
  "Maw(<value> or <custom-param>)": ["max-width: value"],
  "Mih(<value> or <custom-param>)": ["min-height: value"],
  "Miw(<value> or <custom-param>)": ["min-width: value"],
  "Mbm(<custom-param>)": ["mix-blend-mode: value"],
  "Objf(<custom-param>)": ["object-fit: value"],
  "Objp(<value>+ or <custom-param>)": ["object-position: value1 value2"],
  "Orp(<value> or <custom-param>)": ["orphans: value"],
  "O(<custom-param>)": ["outline: value"],
  "Oc(<value> or <custom-param>)": ["outline-color: value"],
  "Oo(<value> or <custom-param>)": ["outline-offset: value"],
  "Os(<custom-param>)": ["outline-style: value"],
  "Ow(<value> or <custom-param>)": ["outline-width: value"],
  "T(<value> or <custom-param>)": ["top: value"],
  "End(<value> or <custom-param>)": ["right: value"],
  "B(<value> or <custom-param>)": ["bottom: value"],
  "Start(<value> or <custom-param>)": ["left: value"],
  "Op(<value> or <custom-param>)": ["opacity: value"],
  "Ov(<custom-param>)": ["overflow: value"],
  "Ovx(<custom-param>)": ["overflow-x: value"],
  "Ovy(<custom-param>)": ["overflow-y: value"],
  "Ovs(<custom-param>)": ["-webkit-overflow-scrolling: value"],
  "P(<value> or <custom-param>)": ["padding: value"],
  "Px(<value> or <custom-param>)": [
    "padding-left: value",
    "padding-right: value",
  ],
  "Py(<value> or <custom-param>)": [
    "padding-top: value",
    "padding-bottom: value",
  ],
  "Pt(<value> or <custom-param>)": ["padding-top: value"],
  "Pend(<value> or <custom-param>)": ["padding-right: value"],
  "Pb(<value> or <custom-param>)": ["padding-bottom: value"],
  "Pstart(<value> or <custom-param>)": ["padding-left: value"],
  "Pc(<custom-param>)": ["place-content: value1 value2"],
  "Pi(<custom-param>)": ["place-items: value1 value2"],
  "Ps(<custom-param>)": ["place-self: value1 value2"],
  "Pe(<custom-param>)": ["pointer-events: value"],
  "Pos(<custom-param>)": ["position: value"],
  "Pca(<custom-param>)": ["print-color-adjust: value"],
  "Rsz(<custom-param>)": ["resize: value"],
  "Sb(<custom-param>)": ["scroll-behavior: value"],
  "Ssa(<custom-param>)": ["scroll-snap-align: value"],
  "Sst(<custom-param>)": ["scroll-snap-type: value"],
  "Sss(<custom-param>)": ["scroll-snap-stop: value"],
  "Sm(<value> or <custom-param>)": ["scroll-margin: value"],
  "Smx(<value> or <custom-param>)": [
    "scroll-margin-left: value",
    "scroll-margin-right: value",
  ],
  "Smy(<value> or <custom-param>)": [
    "scroll-margin-top: value",
    "scroll-margin-bottom: value",
  ],
  "Smt(<value> or <custom-param>)": ["scroll-margin-top: value"],
  "Smend(<value> or <custom-param>)": ["scroll-margin-right: value"],
  "Smb(<value> or <custom-param>)": ["scroll-margin-bottom: value"],
  "Smstart(<value> or <custom-param>)": ["scroll-margin-left: value"],
  "Sp(<value> or <custom-param>)": ["scroll-padding: value"],
  "Spx(<value> or <custom-param>)": [
    "scroll-padding-left: value",
    "scroll-padding-right: value",
  ],
  "Spy(<value> or <custom-param>)": [
    "scroll-padding-top: value",
    "scroll-padding-bottom: value",
  ],
  "Spt(<value> or <custom-param>)": ["scroll-padding-top: value"],
  "Spend(<value> or <custom-param>)": ["scroll-padding-right: value"],
  "Spb(<value> or <custom-param>)": ["scroll-padding-bottom: value"],
  "Spstart(<value> or <custom-param>)": ["scroll-padding-left: value"],
  "Tbl(<custom-param>)": ["table-layout: value"],
  "Ta(<custom-param>)": ["text-align: value"],
  "Tal(<custom-param>)": ["text-align-last: value"],
  "Td(<custom-param>)": ["text-decoration: value"],
  "Tdc(<custom-param>)": ["text-decoration-color: value"],
  "Tds(<custom-param>)": ["text-decoration-style: value"],
  "Tdt(<value> or <custom-param>)": ["text-decoration-thickness: value"],
  "Tuo(<value> or <custom-param>)": ["text-underline-offset: value"],
  "Ti(<value> or <custom-param>)": ["text-indent: value"],
  "Tov(<custom-param>)": ["text-overflow: value"],
  "Tren(<custom-param>)": ["text-rendering: value"],
  "Tr(<custom-param>)": ["text-replace: value"],
  "Tt(<custom-param>)": ["text-transform: value"],
  "Tsh(<custom-param>)": ["text-shadow: value"],
  "Tcha(<custom-param>)": ["touch-action: value"],
  "Trf(<custom-param>)": ["transform: value"],
  "Trfo(<value>+ or <custom-param>)": ["transform-origin: value1 value2"],
  "Trfs(<custom-param>)": ["transform-style: value"],
  "Prs(<value> or <custom-param>)": ["perspective: value"],
  "Prso(<value>+ or <custom-param>)": ["perspective-origin: value1 value2"],
  "Bfv(<custom-param>)": ["backface-visibility: value"],
  "Matrix(<custom-param>)": ["transform: matrix(value)"],
  "Matrix3d(<custom-param>)": ["transform: matrix(value)"],
  "Rotate(<value> or <custom-param>)": ["transform: rotate(value)"],
  "Rotate3d(<value>+ or <custom-param>)": [
    "transform: rotate3d(value1,value2,value3,value4)",
  ],
  "RotateX(<value> or <custom-param>)": ["transform: rotateX(value)"],
  "RotateY(<value> or <custom-param>)": ["transform: rotateY(value)"],
  "RotateZ(<value> or <custom-param>)": ["transform: rotateZ(value)"],
  "Scale(<value>+ or <custom-param>)": ["transform: scale(value)"],
  "Scale3d(<value>+ or <custom-param>)": [
    "transform: scale3d(value1,value2,value3)",
  ],
  "ScaleX(<value> or <custom-param>)": ["transform: scaleX(value)"],
  "ScaleY(<value> or <custom-param>)": ["transform: scaleY(value)"],
  "Skew(<value>+ or <custom-param>)": ["transform: skew(value1,value2)"],
  "SkewX(<value> or <custom-param>)": ["transform: skewX(value)"],
  "SkewY(<value> or <custom-param>)": ["transform: skewY(value)"],
  "Translate(<value>+ or <custom-param>)": [
    "transform: translate(value1,value2)",
  ],
  "Translate3d(<value>+ or <custom-param>)": [
    "transform: translate3d(value1,value2,value3)",
  ],
  "TranslateX(<value> or <custom-param>)": ["transform: translateX(value)"],
  "TranslateY(<value> or <custom-param>)": ["transform: translateY(value)"],
  "TranslateZ(<value> or <custom-param>)": ["transform: translateZ(value)"],
  "Trs(<custom-param>)": ["transition: value"],
  "Trsde(<value> or <custom-param>)": ["transition-delay: value"],
  "Trsdu(<value> or <custom-param>)": ["transition-duration: value"],
  "Trsp(<custom-param>)": ["transition-property: value"],
  "Trstf(<custom-param>)": ["transition-timing-function: value"],
  "Us(<custom-param>)": ["user-select: value"],
  "Va(<value> or <custom-param>)": ["vertical-align: value"],
  "V(<custom-param>)": ["visibility: value"],
  "Whs(<custom-param>)": ["white-space: value"],
  "Whsc(<custom-param>)": ["white-space-collapse: value"],
  "Wid(<value> or <custom-param>)": ["widows: value"],
  "W(<value> or <custom-param>)": ["width: value"],
  "Wc(<value> or <custom-param>)": ["will-change: value"],
  "Wob(<custom-param>)": ["word-break: value"],
  "Wow(<custom-param>)": ["word-wrap: value"],
  "Wm(<custom-param>)": ["writing-mode: value"],
  "Z(<value> or <custom-param>)": ["z-index: value"],
  "Fill(<custom-param>)": ["fill: value"],
  "Stk(<custom-param>)": ["stroke: value"],
  "Stkw(<value> or <custom-param>)": ["stroke-width: value"],
  "Stklc(<custom-param>)": ["stroke-linecap: value"],
  "Stklj(<custom-param>)": ["stroke-linejoin: value"],
};
