name: Changesets
on:
  push:
    branches:
      - main
env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
jobs:
  release:
    if: github.repository == 'ShareChat/atomizer-tailwindcss-migrator'
    timeout-minutes: 15
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.4.0
      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: install dependencies
        run: pnpm install
      - name: save new version
        run: echo "version=cat package.json | jq -r '.version'" >> "$GITHUB_ENV"
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          commit: Version Packages ${env.version}
          title: Release ${env.version}
          publish: pnpm ci:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
